# Generated by Django 3.1.1 on 2020-09-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('language', models.CharField(choices=[('PY', 'Python'), ('RU', 'Ruby'), ('JA', 'Java'), ('JS', 'JavaScript')], default='PY', max_length=2)),
                ('framework', models.CharField(choices=[('FL', 'Flash'), ('DJ', 'Django'), ('SP', 'Springboot'), ('AN', 'Angular')], default='FL', max_length=2)),
            ],
        ),
    ]
