# Generated by Django 3.1.1 on 2020-09-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20200904_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='notes',
            field=models.CharField(blank='True', max_length=1000),
        ),
    ]
