# Generated by Django 3.1.1 on 2020-09-07 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_resource_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
