# Generated by Django 3.1.1 on 2020-09-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20200909_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='journal/attachments/', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='framework',
            field=models.CharField(blank=True, choices=[('Flash', 'Flash'), ('Django', 'Django'), ('SpringBoot', 'SpringBoot'), ('Angular', 'Angular')], max_length=30, verbose_name='Framework'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='language',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('Ruby', 'Ruby'), ('Java', 'Java'), ('JavaScript', 'JavaScript')], max_length=30, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name_text',
            field=models.CharField(max_length=200, verbose_name='Resource name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='notes',
            field=models.CharField(blank='True', max_length=1000, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='post_date',
            field=models.DateField(auto_now_add=True, verbose_name='Post date'),
        ),
    ]
